#ifndef __CMAKE_EXAMPLE_VERSION_H__
#define __CMAKE_EXAMPLE_VERSION_H__

#define VERSIONING_EXAMPLE_MAJOR 1
#define VERSIONING_EXAMPLE_MINOR 0
#define VERSIONING_EXAMPLE_PATCH 0

#endif  __CMAKE_EXAMPLE_VERSION_H__
